import Dashboard from "./pages/Dashboard";
import Upload from "./pages/Upload";
import SearchPage from "./pages/SearchPage";
import Settings from "./pages/Settings";
import Review from "./pages/Review";
import Profile from "./pages/Profile";
import Analytics from "./pages/Analytics";
import Comparison from "./pages/Comparison";
import Auth from "./pages/Auth";
import NotFound from "./pages/NotFound";
import Sidebar from "./components/Sidebar";
import LiquidGlassAI from "./components/LiquidGlassAI";
import LandingPageModal from "./components/LandingPageModal";
import OnboardingModal from "./components/OnboardingModal";
import ProtectedRoute from "./components/ProtectedRoute";
import { SettingsProvider, useSettings } from "./contexts/SettingsContext";
import { AuthProvider } from "./contexts/AuthContext";
import { OnboardingProvider } from "./contexts/OnboardingContext";
import { DemoService } from "./services/demoService";